### ISSUE TITLE
What it does the class js-toc-content?

### ISSUE THREAD

**Issue by alebarbaja** [CodyHouse/cd-table-of-contents-changelog#1]
Hi, I see that on the .js file of this component, there is a typo:

`this.content = document.getElementsByClassName('js-toc-conten')[0];`

The word correct is _js-toc-content_. But besides that, this class doesn't seem being used on the script. Is that correct?

**Comment by claudia-romano** [comment]
Hi Alejandro,
yes that object property was actually unused. We have updated the component and removed it:
https://codyhouse.co/ds/components/app/table-of-contents

Cheers!
