### ISSUE TITLE
Suggestion - Mobile Table of Contents

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-table-of-contents-changelog#2]
Hi Team,

May I suggest an option for displaying the Table of Contents on mobile devices? 
I suggest to do this by including a dropdown button, such as in your [Filter Navigation](https://codyhouse.co/ds/components/app/filter-navigation) component. 

What do you think?

Regards,
Yannick

**Comment by sebastiano-guerriero** [comment]
Good point! We'll look into it.

**Comment by claudia-romano** [comment]
We have pushed an updated version of the component that includes a mobile version:
https://codyhouse.co/ds/components/app/table-of-contents

More about that on the Info page of the component:
https://codyhouse.co/ds/components/info/table-of-contents

Cheers!
