### ISSUE TITLE
Offset content?

### ISSUE THREAD

**Issue by pgroot91** [CodyHouse/cd-table-of-contents-changelog#4]
Hi guys, 

is there a way to set also an offset for the content so the content doesn't scroll completely to the top of the viewport behind the fixed header?

**Comment by claudia-romano** [comment]
Hi there,
the TOC uses the [Smooth Scrolling component](https://codyhouse.co/ds/components/app/smooth-scrolling) for the scrolling behaviour. 

Here's how to fix the issue with fixed elements when using the Smooth Scrolling component:
https://codyhouse.co/ds/components/info/smooth-scrolling#fixed-element

Cheers!

**Comment by pgroot91** [comment]
@claudia-romano thanks! 

That worked like a charm 👍 

My issue is solved.
