### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by madsfors** [CodyHouse/cd-table-of-contents-changelog#5]
1. Internet explorer is not using the desktop version of the navigation and doesn't accept any clicks on the "in this article" button.
2. It's not working in the demo nor when trying to setup locally
3. Internet Explorer 11 on Windows 10 Pro
4. https://codyhouse.co/ds/components/app/table-of-contents + https://madsfors.dk/Attain%20WebControl%20What's%20Inside%20Article/
5. https://user-images.githubusercontent.com/2444115/116992920-0ebac780-acd7-11eb-94d1-03fe79cec83c.mp4

**Comment by claudia-romano** [comment]
Hi there, we have just pushed an updated version of the component that fixes the issue on IE11.

Cheers!
